Add error-boundary and errors pages
yandex-team-08/wonderful-game pull request #10
Opened 2022-12-11 20:26 UTC by innabatalova

### Какую задачу решаем
Сверстала страницы обработки ошибок (404 и 500), пока к роутеру они не подключены.
Добавила библиотеку обработки ошибок (react-error-boundary) внутри React-компонентов, добавила интерфейс при ошибку компонента с кнопкой перезагрузки родительского компонента. 

### Скриншоты/видяшка (если есть)
![Снимок экрана от 2022-12-11 23-06-26](https://user-images.githubusercontent.com/79709718/206926797-1f038292-30e6-4368-b0e0-04583c1e6040.png)

![Снимок экрана от 2022-12-11 23-22-31](https://user-images.githubusercontent.com/79709718/206926930-d730617c-3fc4-4cb8-bb13-c509faad1f22.png)

### TBD (если есть)
Пока обернула в обработчик только компонент на странице логина, если с кодом все ок- оберну все необходимые.

2022-12-12 11:15 UTC, caspa2289 reviewed
Проделана хорошая работа, но перед слиянием необходимо корректно подключить компоненты ошибок к роутеру, и поправить минорные замечания.

2022-12-12 11:15 UTC, caspa2289 commented on package.json
> +    "@types/react": "^18.0.26"
Для чего это было добавлено?

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-404/Error-404.tsx
> +import BGMain from '../../../../public/BG-main.jpg';
Лучше конвертировать в .webp, в принципе даже как фолбэк жипег необязателен для нашего проекта.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-404/Error-404.tsx
> +  const style = { background:'url(../../' + BGMain + ')', backgroundSize: 'cover' };
Это надо в стили вынести.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-404/Error-404.tsx
> +    <span className={styles.span}>Не туда попали...</span>
В mui есть компонент Typography, в этом случае стилизацию удобнее сделать через него будет. Не нужно будет так много стилей переписывать. Плюс, если будет необходимость накинуть темы, не нужно будет вносить никаких правок в компонент.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-404/index.ts
> +export { default } from './Error-404';
Файлы компонентов именуются в PascalCase. Файлы стилей именуются *ИмяКомпонента*.module.scss

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-500/Error-500.tsx
> +  const style = { background:'url(../../' + BGMain + ')',backgroundSize: 'cover' };
Нужно вынести в стили

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-500/Error-500.tsx
> +    <a href={ROUTE_PATHS.login} className={styles.a}>назад в игру</a>
Нужно использовать useNavigate(). Здесь перезагрузка страницы не нужна.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error-500/index.ts
> +export { default } from './Error-500';
PascalCase.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/Error.module.scss
> +    font-size: 96px;
Хардкодить размеры шрифтов не лучшая практика даже в нашем случае. Такие большие буквы даже при небольшой разнице в размерах экрана будут смотреться очень по-разному. Используй rem или em. Возможно от большинства этих стилей можно вообще отказаться, использовав Typography https://mui.com/material-ui/react-typography/

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/utils/ErrorBoundary.tsx
> +      <button className={styles.button} onClick={resetErrorBoundary} >Обновить</button>
Используй Button из mui, если есть необходимость в кастомизации https://mui.com/material-ui/customization/how-to-customize/#1-one-off-customization, но для целей нашего проекта думаю дефолтных тем достаточно будет.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/utils/ErrorBoundary.module.scss
> +    color: #1976d2;
Не нужно при использовании mui Button.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Errors/utils/ErrorBoundary.tsx
> +export function ErrorFallback({ error,resetErrorBoundary }: ErrorType) {
Имя файла должно совпадать с именем компонента. В данном случае лучше подойдёт название типа RuntimeError.
Почему этот компонент лежит в utils?

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Login/Login.tsx
> +  //логика для тестирования ErrorBoundary
Комментарии нужно потереть.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/pages/Login/Login.tsx
> +        <ErrorBoundary FallbackComponent={ErrorFallback} >
В ErrorBoundary нужно обернуть компонент Root. Все прочие роуты являются его чилдренами.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/types/errorType.ts
> +export type ErrorType = { error: Error, resetErrorBoundary: () => any };
Стоит избегать использования any.

2022-12-12 11:15 UTC, caspa2289 commented on packages/client/src/utils/routes.tsx
> +  children: [LOGIN, SIGNUP, GAME, ERROR404],
Компоненты ошибок надо прокинуть в объявления роутов, а не в роутер. Сама по себе страница ошибки это фолбэк, а не самостоятельная страница. https://reactrouter.com/en/main/route/error-element. Сейчас на них можно зайти просто по ссылке.

2022-12-12 12:57 UTC, kirka-dev commented on packages/client/src/pages/Errors/Error.module.scss
> +}
Стили прописаны не к классам.

Не помню, мы вроде не обсуждали, но вроде негласно используем БЭМ.

2022-12-12 15:19 UTC, AntLer-24rus requested changes
Хорошая работа! Необходимо учесть жамечания и можно мержить. Также не стоит упускать что не прошел CI а именно упали тесты. Необходимо добавить в `jest` мок на картинки.

2022-12-12 15:19 UTC, AntLer-24rus commented on packages/client/src/pages/Errors/utils/ErrorBoundary.tsx
> +export function ErrorFallback({ error,resetErrorBoundary }: ErrorType) {
Я бы еще рекомендовал пропсы деструктурировать уже внутри компонента, если их будет много это затруднит чтение.

что-то подобное:
```js
export function ErrorFallback(props: ErrorType) {
const { error,resetErrorBoundary } = props;
}
```

2022-12-12 15:19 UTC, AntLer-24rus commented on packages/client/src/pages/Errors/Error.module.scss
> +}
Поддерживаю, стили лучше писать классами, не тегами за очень редким исключением

2022-12-12 15:19 UTC, AntLer-24rus commented on packages/client/src/types/errorType.ts
> +export type ErrorType = { error: Error, resetErrorBoundary: () => any };
По смыслу тут можно использовать `void`

2022-12-13 05:04 UTC, AntLer-24rus approved these changes
Есть незначительные комментарии, если ты перфекционист поправь =) А так с моей стороны все ок, оперативно исправлены все замечания.  🔥

2022-12-13 05:04 UTC, AntLer-24rus commented on packages/client/src/pages/Root/Root.tsx
> +  // </Button>
Если это логика тестирования, напишите тогда тесты чтоли. Закомментированный код хранить в репозитории плохая практика.

2022-12-13 08:35 UTC, innabatalova commented on packages/client/src/pages/Root/Root.tsx
> +  // </Button>
Да, сорри, это я из Login удалила, а тут просмотрела, уберу комменты

2022-12-13 08:50 UTC, lizgam reviewed
А в этот PR включена еще и задача с профилем пользователя? (или я чего-то не поняла)
И еще тогда страница профиля не отличается ничем от страницы логина.

2022-12-13 09:04 UTC, innabatalova commented
> А в этот PR включена еще и проблема с профилем пользователя? (или я чего-то не понял) И еще тогда страница профиля ничем не отличается от страницы логина.

Нет, профиль не включен в этот ПР, это у меня какой то сбой, уберу все что отновится к профилю

2022-12-13 10:06 UTC, innabatalova commented
Так, теперь должно быть норм

2022-12-13 16:56 UTC, lizgam approved these changes

2022-12-18 08:04 UTC, AntLer-24rus approved these changes
👌🏻

2023-01-13 13:08 UTC, edelweissvalley approved these changes

2023-02-09 12:26 UTC, closed without merging