add leaderboard page
yandex-team-08/wonderful-game pull request #11
Opened 2022-12-12 05:57 UTC by lizgam

### Какую задачу решаем
Добавлена страница Лидерборда

### Скриншоты/видяшка (если есть)
<img width="944" alt="Screenshot 2022-12-11 at 9 25 10 PM" src="https://user-images.githubusercontent.com/22134839/206970931-340f1d4b-5eba-4d02-bf02-301111eda2f8.png">

### TBD (если есть)

2022-12-12 11:33 UTC, caspa2289 requested changes
Хорошая база для будущей страницы, перед слиянием нужно исправить небольшие замечания.

2022-12-12 11:33 UTC, caspa2289 commented on .gitignore
> +**/.DS_Store
Для чего это нужно?

2022-12-12 11:33 UTC, caspa2289 commented on packages/client/src/pages/Leaderboard/Leaderboard.module.scss
> +    height: 90%;
Высота хедера фиксированная, 64px, при задании высоты враппера в процентах, он не всегда будет занимать всё доступное место.

2022-12-12 11:33 UTC, caspa2289 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                        {(rows.map((row) => (
Этот список нужно мемоизировать. Если при запросе на сервер придёт тот же список, ререндер не нужен, но в текущей реализации он будет. 
Возвращаемое здесь значение (TableRow) я бы посоветовал вынести в отдельный компонент, для лучшей читаемости.
Пропсы лучше деструктурировать, вместо `(row) =>` использовать `({ user, score }) =>`

2022-12-12 11:33 UTC, caspa2289 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +const rows = [
FYI: компонент должен идти последним объявлением в файле, для лучшей читаемости.

2022-12-12 11:33 UTC, caspa2289 commented on packages/client/src/utils/routes.tsx
> +  list: [ROUTE_PATHS.login, ROUTE_PATHS.signup, ROUTE_PATHS.game, ROUTE_PATHS.leaderboard],
Авторизованным пользователям он тоже должен быть доступен, надо добавить в AUTHORIZED_ROUTES

2022-12-12 15:04 UTC, AntLer-24rus requested changes
Все здорово! 👍 Но я бы рекомендовал пользоватся одним из инструментов, либо `npm` либо `yarn`, поскольку у вас проект изначально построен с `yarn` то им и нужно пользоватся. Это комментарий в сторону файла `package-lock.json`

2022-12-12 15:04 UTC, AntLer-24rus commented on .gitignore
> +**/.DS_Store
системные файлы на macOS, тут все от

2022-12-14 03:43 UTC, lizgam commented
комментарии к ПР исправлены

2022-12-17 10:09 UTC, caspa2289 approved these changes
У меня замечаний нет, хорошая работа.

2022-12-17 18:17 UTC, kirka-dev reviewed
Все хорошо, только одно маленькое замечание

2022-12-17 18:17 UTC, kirka-dev commented on packages/client/src/components/TableLeader/TableLeader.tsx
> +});
По-моему компонента должна лежать в pages/Leaderboard/components

2022-12-17 23:21 UTC, lizgam commented on packages/client/src/components/TableLeader/TableLeader.tsx
> +});
Верно, я перемещу.

2022-12-18 08:09 UTC, kirka-dev approved these changes

2022-12-18 08:48 UTC, AntLer-24rus approved these changes
👌🏻 все ок, замечаний нет

2022-12-18 08:52 UTC, merged