add forum
yandex-team-08/wonderful-game pull request #12
Opened 2022-12-16 11:15 UTC by kirka-dev

### Какую задачу решаем
Добавил форум и отдельную страницу

### Скриншоты/видяшка (если есть)
<img width="1512" alt="Снимок экрана 2022-12-16 в 15 13 34" src="https://user-images.githubusercontent.com/70610047/208086574-b88fcb0b-00f1-450d-9ef6-764b61aea1cc.png">
<img width="1512" alt="Снимок экрана 2022-12-16 в 15 13 45" src="https://user-images.githubusercontent.com/70610047/208086592-8ee5d1dc-cf9d-4507-863b-de1534568c99.png">

### TBD (если есть)

2022-12-17 09:04 UTC, caspa2289 requested changes
Хорошая работа, нужно только поправить логику роутинга по страницам форума и исправить проблемы с линтером

2022-12-17 09:04 UTC, caspa2289 commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +          {MOCK.messages && MOCK.messages.map(message => <Message key={message.id}
Нужно мемоизировать. 
Пропсы нужно либо деструктурировать, либо передать как <Message key={message.id} {...message} />. Для читаемости.

2022-12-17 09:04 UTC, caspa2289 commented on packages/client/src/pages/ForumPage/components/Message/Message.tsx
> +const Message: FC<ForumPageProps> = (props) => {
Пропсы нужно деструктурировать.

2022-12-17 09:04 UTC, caspa2289 commented on packages/client/src/pages/ForumPage/components/MessageField/MessageField.tsx
> +      <TextField fullWidth
У тебя с настройками линтера по-моему что-то не так

2022-12-17 09:04 UTC, caspa2289 commented on packages/client/src/utils/routes.tsx
> +  children: [LOGIN, SIGNUP, GAME, FORUM, FORUM_PAGE],
FORUM_PAGE по идее должна быть чилдреном FORUM, плюс нужен роутинг до конкретного поста.
https://reactrouter.com/en/main/start/tutorial#nested-routes

2022-12-17 09:04 UTC, caspa2289 commented on packages/client/src/pages/Forum/Forum.tsx
> +                                                    id={post.id}
Это линтер так поправил? Выглядит как будто у тебя настройки не правильные.

2022-12-18 08:16 UTC, AntLer-24rus approved these changes
С моей стороны все ок 🔥 Единственное разобраться с замечаниями про линтер/приттер.

P.S.: не стоит коммитить пустые файлы, в этом нет смысла никакого.

2022-12-18 08:16 UTC, AntLer-24rus commented on packages/client/src/pages/Game/Game.tsx
> +  );
Не очень понимаю смысл этих изменений. Здесь только стиль кода изменен, у вас в проекте должны же быть единые настройки как приттера так и линтера. + Уже были комментарии к настройке линтера.

2022-12-19 06:39 UTC, caspa2289 approved these changes
У меня замечаний нет

2022-12-19 08:26 UTC, merged