add redux
yandex-team-08/wonderful-game pull request #13
Opened 2022-12-16 22:35 UTC by kirka-dev

### Какую задачу решаем
Добавил redux подключил к нему состояние игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-17 09:23 UTC, caspa2289 requested changes
Молодец, проделал большую работу, но нужно поправить типизацию и небольшие замечания.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/pages/Game/Game.tsx
> +  const status = useSelector((state: { game: gameInterface }) => state.game.status);
Нужно вынести это в селектор. Инлайновые селекторы это плохая практика. Типизация тут не нужна была бы, если бы было типизировано хранилище.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/pages/Game/Game.tsx
> +  const dispatch = useDispatch();
Диспатч нужно типизировать. Стор не типизирован, поэтому тс не ругается.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/pages/Game/Game.tsx
> +        [gameStateEnum.START]: <Button onClick={() => dispatch(loading())} variant="outlined">Играть</Button>,
Верни handleStartGame, инлайновые колбэки это плохая практика.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/reducers/game.reducer.ts
> +  name: 'counter',
`name: 'counter' ` :)

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/reducers/game.reducer.ts
> +    start: (state: gameInterface) => {
Тут нужен один экшен типа setGameState, который может принимать три значения старт, лоудинг и плей. Плей я бы назвал "ready", так понятнее что он значит. Пэйлоуды нужно будет типизировать.

Если у тебя большой объект, в котором несколько сущностей, и ты не можешь разделить его на отдельные свойства, имеет смысл создавать экшены, которые меняют только одну сущность в этом объекте, но если три экшена меняют одно и то же конкретное свойство, это плохой подход.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/reducers/game.reducer.ts
> +  initialState: {
initialState нужно типизировать

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/types/game.interface.ts
> +export interface gameInterface {
Интерфейсы обозначают I*имя*, типы T*имя*, либо вообще никак не обозначают, мне лично первый вариант больше нравится.

2022-12-17 09:23 UTC, caspa2289 commented on packages/client/src/types/game.interface.ts
> +  status: gameStateEnum;
Это лишний интерфейс, нужно типизировать слайс.

2022-12-18 08:24 UTC, AntLer-24rus requested changes
Поддерживаю @caspa2289 необходимо добавить типизацию стора.

2022-12-21 15:06 UTC, caspa2289 approved these changes

2022-12-23 12:51 UTC, AntLer-24rus approved these changes
Все 🔥

2022-12-23 12:52 UTC, merged