Task/20 t08 3/add profile
yandex-team-08/wonderful-game pull request #16
Opened 2022-12-22 08:46 UTC by innabatalova

### Какую задачу решаем
Добавила страницу профиля, возможность менять данные через попап, отправку запросов для замены данных.

### Скриншоты/видяшка (если есть)

### TBD (если есть)
Не могу понять, почему не получается менять аватар, приходит ответ 400 (неверный формат данных), подскажите, плиз, как привести к нужному формату.

2022-12-23 07:38 UTC, caspa2289 requested changes
Молодец, большая работа проделана, но нужно избавиться от лишних зависимостей и файлов в репо.

2022-12-23 07:38 UTC, caspa2289 commented on lerna-debug.log
> +0 silly argv {
Логи не нужны в репо

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/package.json
> +    "formik-file-and-image-input": "^0.0.6",
Не думаю, что нам тут это нужно. Инпуты из mui можно использовать для этих целей. https://stackoverflow.com/questions/40589302/how-to-enable-file-upload-on-reacts-material-ui-simple-input
 Ну и либа, у которой последнее обновление было год назад и версия 0.0.6 это нежелательная зависимость в любом случае.

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/package.json
> +    "reactjs-popup": "^2.0.5",
Ненужная зависимость. https://mui.com/material-ui/react-modal/

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/api/user.ts
> +    display_name: string | undefined
Вместо `display_name: string | undefined` должно быть `display_name?: string`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/global.d.ts
> +declare module 'formik-file-and-image-input/lib';
Это лишнее

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/hooks/useSetting.ts
> +      navigate(ROUTE_PATHS.setting);
Это не то, что стоило делать, но сейчас думаю смысла переделывать нет, всё равно на редакс авторизацию перевозить.

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/hooks/useSetting.ts
> +  const profile = useCallback(async (values: IUserProfileChange) => {
Названия функций должны начинаться с глагола, который поясняет, что функция делает.

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/ProfilePage/components/PopupAvatar/PopupAvatar.module.scss
> +    transform: translate(-50%, -50%) !important;
`position: absolute !important;
    top: 50% !important;
    left: 50% !important;
    transform: translate(-50%, -50%) !important;`
Используй гриды, если совсем никак, такой хардкод это плохая практика.

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/ProfilePage/components/PopupAvatar/utils/validationSchema.ts
> +    image: mixed().required(FIELD_REQUIRED),
Оно обязательно разве? Возможность удалить аватар отдельно реализована?

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/ProfilePage/components/PopupProfileData/PopupProfileData.module.scss
> +    transform: translate(-50%, -50%);
Зачем?

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/ProfilePage/components/PopupProfileData/PopupProfileData.tsx
> +            <div  className={styles.wrapper}>
Два пробела, проверь настройки линтера

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/ProfilePage/components/PopupProfilePassword/PopupProfilePassword.tsx
> +                <FormikTextField name="oldPassword" label="Старый пароль" />
type="password"

2022-12-23 07:38 UTC, caspa2289 commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +  const avatarSrc = useMemo(
Это всё нужно вынести в отдельный компонент <CustomAvatar/> и переиспользовать его.

2022-12-23 07:38 UTC, caspa2289 commented on packages/server/package.json
> +    "formik-file-and-image-input": "^0.0.6",
Для сервера это не нужно. Когда устанавливаешь зависимости, указывай соответствующий scope.

2022-12-23 07:38 UTC, caspa2289 commented on packages/server/package.json
> +    "reactjs-popup": "^2.0.5"
Это тоже не нужно.

2023-01-13 14:14 UTC, edelweissvalley requested changes

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +  const { first_name, second_name, display_name, avatar } = userInfo ?? {};
Здесь достаточно
const { first_name, second_name, display_name, avatar } = userInfo || {};

2023-01-13 14:14 UTC, edelweissvalley commented on packages/server/package.json
> +    "@types/react": "^18.0.26",
Это лишнее

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/src/pages/ProfilePage/components/PopupAvatar/PopupAvatar.module.scss
> +#button{
Лучше обойтись классом

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/package.json
> +    "@types/react": "^18.0.26",
Для реакта типы подтягиваются как подзависимость, следить самостоятельно за актуальностью версии типов - лишнее.

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/src/pages/ProfilePage/components/PopupProfilePassword/PopupProfilePassword.tsx
> +    const initialValues = {
У Формика есть состояние поля touched. Для того, чтоб оно корректно работало - лучше задавать по-умолчанию undefined.

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +  const avatarSrc = useMemo(
Вынести отдельно

2023-01-13 14:14 UTC, edelweissvalley commented on packages/client/src/pages/ProfilePage/components/ProfileField/ProfileField.tsx
> +const ProfileField : FC<IMainProfileFieldProps> = ({ fieldName, fieldText }) =>  {
Чёт форматирование поехало

2023-01-20 08:36 UTC, innabatalova commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +  const avatarSrc = useMemo(
А что тут нужно вынести отдельно?

2023-01-30 15:27 UTC, AntLer-24rus requested changes
Хорошая работа! Но есть кажется проблемы с настройкой prettier. В разных местах код немного па разному отформатирован. Также хочу акцентировать отсутствие пустых строк в конце файлов css

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/components/AvatarComponent/AvatarComponent.tsx
> +    () => (!AvatarComponentAPI ? '/' : AvatarComponentAPI + avatar),
Не совсем понял в каком случае `AvatarComponentAPI` может быть не задан

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +  const { first_name, second_name, display_name } = userInfo || {};
Чем не понравился оператор нулевого слияния? (??). Также стоило бы задать значения в случае отсутствия `userInfo`, а то получится что `nameString` будет вида `undefined undefined`, это мелочи конечно но все же.

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/components/AvatarComponent/AvatarComponent.tsx
> +export default AvatarComponent;
На мой взгляд все таки лучше именованный экспорт, проще потом рефакторить. Но тут уже как у вас в команде заведено.

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/api/user.ts
> +    first_name: string | undefined
При таком задании типа я понимаю что `first_name` в значении `undefined` является валидным вариантом?

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +      </div>
Кажется съехало форматирование

2023-01-30 15:27 UTC, AntLer-24rus commented on packages/client/src/pages/ProfilePage/components/PopupAvatar/PopupAvatar.tsx
> +        <Button variant='contained' type='button' sx={{ marginBottom: '25px' }} onClick={handleOpen} className={styles.button}>{buttonText}</Button>
Можно и нужно отформатировать каждый props в отдельную строку, будет легче читать

2023-02-02 15:58 UTC, AntLer-24rus reviewed
Насколько смог увидеть кодстайл подправлен. Остался только вопрос к файлику `packages/client/src/components/AvatarComponent/AvatarComponent.tsx`

2023-02-02 15:58 UTC, AntLer-24rus commented on packages/client/src/components/AvatarComponent/AvatarComponent.tsx
>    );
Объясни пожалуйста какая логика работы этой функции?

2023-02-10 12:26 UTC, AntLer-24rus approved these changes

2023-02-10 12:26 UTC, AntLer-24rus commented on packages/client/src/utils/constants.ts
> +export const TEAM_NAME = 'team8';
А это правильно что константа `USER_API` удалена?

2023-02-12 17:38 UTC, closed without merging