Task 20 t08 2/add authorisation
yandex-team-08/wonderful-game pull request #2
Opened 2022-11-28 10:53 UTC by caspa2289

### Какую задачу решаем
Добавил бойлерплейт для аутентификации и провайдер контекста страницы, даунгрейднул версию ноды чтобы гх тесты работали. Надо уточнить, можно ли просто апнуть версию в тестах, это предпочтительнее.

2022-12-01 00:16 UTC, lizgam commented on packages/client/src/pages/Root/Root.module.scss
> +  aspect-ratio: 16/9;
предлагаю регулировать высоту блока содержимым контента

2022-12-01 00:34 UTC, lizgam commented
если договоренности по поводу делать все одним большим коммитом все еще в силе - то надо засквошить все коммиты в один. А так - с моей стороны все ок)) Хорошая работа!

2022-12-01 01:37 UTC, edelweissvalley reviewed
Задача была добавить авторизацию/регистрацию.
В первой итерации можно без api.

По итогу изменено/добавлено 45 файлов, которые просматривать крайне неудобно.
Сюда же всунуто уйма лишнего функционала, не предусмотренного задачей.

Pr необходимо разбить на более мелкие части для более гибкой и удобной работы всех участников проекта.

2022-12-01 01:37 UTC, edelweissvalley commented on packages/client/package.json
> +    "@emotion/react": "^11.10.5",
Зачем столько пакетов?
Достаточно же одного material

2022-12-01 01:58 UTC, edelweissvalley requested changes

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/package.json
> +    "axios": "^1.2.0",
Для реакта лучше подходит reaqt-query

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/package.json
> +    "react-router": "^6.4.3",
Это не нужно, "react-router-dom" подтянет его сам

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const inputValue = (values as Record<string, never>)[name]
Через useField можно сразу вытянуть  всё, что касается данного поля

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const handleChange = useCallback((event: BaseSyntheticEvent) => {
В данном случае нет необходимости оборачивать в useCallBack

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +      onChange={handleChange}
onChange должен быть опциональным и иметь возможность перезаписываться.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +      variant="outlined"
Обёрткой надо добавлять ф-нал и не ограничивать изнутри.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/Formik/FormikTextField/index.ts
> +export { default } from './FormikTextField'
Дефолтные экспорты я прикрыл линтом, т.к. все начнут называть компоненты при импорте как придётся и это усложнит рефакторинг.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/components/PageWrapper/PageWrapper.module.scss
> +.wrapper {
Для чего scss?
Его функционал как-то используется?

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/hooks/useRootLoaderData.ts
> +export const useRootLoaderData = () =>
В чём смысл этой обёртки?

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/pages/Game/Game.tsx
> +  const { setPageName } = useOutletContext<IOutletContext>()
2 хука для 1 заголовка?
Лучше их отдельно хранить и переключать из обёртки над страницами

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +import { usePageContext } from '../../../../../../../hooks/usePageContext'
Надо подумать, как прикрутить алиасы.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +  const nameString = useMemo(
Зачем useMemo?
Никаких тяжёлых расчётов здесь не происходит.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Unauthorized/Unauthorized.tsx
> +  const handleSignupClick = useCallback(() => {
useCallback здесь лишний

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/utils/routes.tsx
> +export const ROUTE_PATHS = {
Это в enum хранить надо.

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/utils/routes.tsx
> +const LOGIN: NonIndexRouteObject = {
А список страниц - в массиве

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/utils/routes.tsx
> +export const rootLoader: TRootLoader = async () => {
react-query подойдёт лучше

2022-12-01 01:58 UTC, edelweissvalley commented on packages/client/src/utils/sessionStorage.ts
> +export const setSessionStorage = (key: string, value: unknown) => {
не используется

2022-12-01 05:35 UTC, caspa2289 commented on packages/client/package.json
> +    "@emotion/react": "^11.10.5",
Подтягивал как в доке описано, https://mui.com/material-ui/getting-started/installation/
Если я что-то недопонял, укажи, куда читать, вроде всё ок.
Там ещё шрифт говорят установить, этого я не сделал почему-то.

2022-12-01 05:42 UTC, caspa2289 commented on packages/client/package.json
> +    "axios": "^1.2.0",
Для чистого реакта - согласен, для редакса он избыточен. А нам придётся использовать редакс по курсу, насколько я помню.

2022-12-01 05:56 UTC, caspa2289 commented on packages/client/src/components/PageWrapper/PageWrapper.module.scss
> +.wrapper {
Облегчает муки нейминга.

2022-12-01 06:04 UTC, caspa2289 commented on packages/client/src/hooks/useRootLoaderData.ts
> +export const useRootLoaderData = () =>
Типизировать ответ (): unknown

2022-12-01 06:12 UTC, caspa2289 commented on packages/client/src/pages/Game/Game.tsx
> +  const { setPageName } = useOutletContext<IOutletContext>()
Плюсую. Идея была сделать обёртку, которую можно один раз сделать и забыть. Хотелось бы обойтись вообще без сеттеров, но у меня нет идей как это сделать. Пропсы достать из роутера либо нельзя, либо я не понял, как это сделать. Если знаешь что можно покурить на эту тему, буду благодарен.

2022-12-01 06:13 UTC, caspa2289 commented on packages/client/src/pages/Root/Root.module.scss
> +  aspect-ratio: 16/9;
Карточка тогда будет в размере меняться на разных страницах. Либо всё равно надо будет ограничивать размер контента.

2022-12-01 16:24 UTC, AntLer-24rus requested changes
Довольно объемная работа проделана! Есть несколько замечаний и уточнений, но в целом все круто! Хочется отметить что неплохо придерживаться единого стилия в написании выходных переменных и т.д. смотри коменты. Также прошу на будущее когда ревьюите друг друга писать боле развернутые сообщения с предложениями как можно сделать по другому. Что какаеться ПР, есть необходимость в некоторых местах исправить. см. комменты

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const { values, setFieldValue, errors } = useFormikContext()
`useFormikContext` позволяет передеть дженерик тип, например `useFormikContext<{name: string}>` и не нужно было бы преобразовывать в 18 и 19 строках.

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const inputValue = (values as Record<string, never>)[name]
Здорово было бы привести коротенький пример как это можно сденлать.

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const handleChange = useCallback((event: BaseSyntheticEvent) => {
Также было бы неплохо объяснить почему в данном случе нет необходимости.

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +      variant="outlined"
Необязательно, обертка может наоборот сузить функционал задав как-то свойства по умолчанию, зависит от контекста использования.

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +      onChange={handleChange}
Так же прокомментируй почему так должно быть. Это полезно, и сам формализуешь знание и сокомандники почитают или даже узнают что-то новое =)

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/Formik/FormikTextField/index.ts
> +export { default } from './FormikTextField'
Дефолтный или именованный экспорт это вечная война. Договаривайтесь как вашей команде будет удобнее. Если есть правила в линтере вообще отлично!

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/PageWrapper/PageWrapper.tsx
> +    if (isRoot || !getIsAuthorisedToAccessPage(location, userRoutes.list)) {
getIsAuthori`z`edToAccessPage - опечатка

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/components/PageWrapper/PageWrapper.tsx
> +const PageWrapper: FC<{ children: ReactNode }> = ({ children }) => {
Не ленитесь выносить это в отдельный тип, например `type PageWrapperProps = { children: ReactNode }`

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/hooks/useAuth.ts
> +      //FIXME: если роутить на логин, не стреляет запрос к /user
если столкнулись со странным поведением или не можете решить задачу создавайте issue и на командном созвоне договаривайтесь кто и как ее решает. А такого рода коментарии не хорошо пушить в основную ветку разработки, есть вариант забыть их там навсегда..

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/hooks/useAuth.ts
> +    logout: logoutAction,
Неплохо было бы соблюдать единую систему нейминга

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/hooks/useRootLoaderData.ts
> +export const useRootLoaderData = () =>
конструкция `as` может выстрелить в runtime`е, вы точно уверены что эти поля всегда будут?

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/pages/Login/Login.tsx
> +  //FIXME: разобраться, как можно в роутер пропсом прокинуть имя, чтобы на уровне провайдера его достать
Уже упомянал о таких комментариях.

2022-12-01 16:24 UTC, AntLer-24rus commented on README.md
> +1. Убедитесь, что версия ноды `^16.8.1`. Если нужно менеджить несколько версий ноды: [Шиндовс](https://github.com/nvm-sh/nvm#installing-and-updating) | [Мак/линукс](https://sdkman.io/install)
Зачем понижали версию ноды?

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +  const { first_name, second_name, display_name, avatar } = userInfo ?? {}
Лучше не доставать переменные из объекта которые не будут использоваться в дальнейшем.

2022-12-01 16:24 UTC, AntLer-24rus commented on packages/client/src/utils/routes.tsx
> +export const rootLoader: TRootLoader = async () => {
Поясни почему так думаешь.

2022-12-02 15:57 UTC, caspa2289 commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +  const inputValue = (values as Record<string, never>)[name]
> Здорово было бы привести коротенький пример как это можно сденлать.

const [field, meta, helpers] = useField(name)
В field хранится всё связанное со значением, в meta всё связанное с валидацией, в helpers сеттеры.

2022-12-02 16:04 UTC, caspa2289 commented on packages/client/src/components/Formik/FormikTextField/FormikTextField.tsx
> +      variant="outlined"
> Необязательно, обертка может наоборот сузить функционал задав как-то свойства по умолчанию, зависит от контекста использования.

Тут наверное имеется в виду, что variant надо дефолтить на outlined, а не хардкодить. Остальное ограничено намеренно.

2022-12-02 16:05 UTC, caspa2289 commented on packages/client/src/hooks/useRootLoaderData.ts
> +export const useRootLoaderData = () =>
> конструкция `as` может выстрелить в runtime`е, вы точно уверены что эти поля всегда будут?

Да, я их руками туда прокидываю.

2022-12-02 16:08 UTC, caspa2289 commented on packages/client/src/hooks/useAuth.ts
> +      //FIXME: если роутить на логин, не стреляет запрос к /user
> если столкнулись со странным поведением или не можете решить задачу создавайте issue и на командном созвоне договаривайтесь кто и как ее решает. А такого рода коментарии не хорошо пушить в основную ветку разработки, есть вариант забыть их там навсегда..

Это не основная ветка.

2022-12-02 16:11 UTC, caspa2289 commented on README.md
> +1. Убедитесь, что версия ноды `^16.8.1`. Если нужно менеджить несколько версий ноды: [Шиндовс](https://github.com/nvm-sh/nvm#installing-and-updating) | [Мак/линукс](https://sdkman.io/install)
> Зачем понижали версию ноды?

Тесты работают на 16 ноде. Надо либо в тестах апать версию, либо опускать версию ноды. Изначально никакого требования не было, 18 тоже я поставил. Так что проблемы в этом не вижу.

2022-12-02 16:14 UTC, caspa2289 commented on packages/client/src/hooks/useAuth.ts
> +    logout: logoutAction,
> Неплохо было бы соблюдать единую систему нейминга

Не понимаю, о чём речь

2022-12-04 07:55 UTC, AntLer-24rus commented on packages/client/src/hooks/useAuth.ts
> +      //FIXME: если роутить на логин, не стреляет запрос к /user
Хочешь сказать в этой ветке `release-1` разрабатываешь только ты один? Тогда как у вас построена командная работа? Этот коммент был не камнем в огород, а хорошей практикой работы в команде.

2022-12-04 07:58 UTC, AntLer-24rus commented on packages/client/src/hooks/useAuth.ts
> +    logout: logoutAction,
По смыслу у тебя есть две функции, логин и логаут, одна названа `const login = useCallback(async (data: IUserSigninReq) => {` вторая `const logoutAction = useCallback(async () => {` а на эаспорте это превращается
```js
return {
  login,
  logout: logoutAction,
  }
```
Так почему не назвать функции одинаково, `loginAction`, `logoutAction` или `login`, `logout`?

2022-12-07 06:43 UTC, closed without merging

2022-12-07 07:26 UTC, caspa2289 commented on packages/client/src/hooks/useAuth.ts
> +      //FIXME: если роутить на логин, не стреляет запрос к /user
> Хочешь сказать в этой ветке `release-1` разрабатываешь только ты один? Тогда как у вас построена командная работа? Этот коммент был не камнем в огород, а хорошей практикой работы в команде.

Да, хочу) На тот момент ещё не решили, как у нас флоу будет выглядеть вообще. Сейчас решили, что разрабатываем в ветке dev.