Task/20 t08 71/add web audio api
yandex-team-08/wonderful-game pull request #21
Opened 2023-01-23 20:13 UTC by innabatalova

### Какую задачу решаем
Добавила Web API Audio для проигрыша фоновой мелодии.

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/79709718/214140100-479c9623-2e57-4c05-8263-5b0102d8fbe6.png)

![image](https://user-images.githubusercontent.com/79709718/214140168-54e805f7-d7a4-4fc5-a626-9df12fb67a73.png)

### TBD (если есть)

2023-01-25 07:03 UTC, caspa2289 commented on packages/client/src/pages/Game/components/AudioButton/AudoiButton.tsx
> +    <audio ref={audioElement} src='../../src/audio/main-sound.mp3' />
С настройками линтера что-то не то, вложенность отступами не обозначена.

2023-01-25 07:03 UTC, caspa2289 commented on packages/client/src/pages/Game/components/AudioButton/index.ts
> +export { default } from './AudoiButton';
Опечатка в слове Audio

2023-01-30 15:41 UTC, AntLer-24rus requested changes
Очень много чисто стилистических правок, непонятно что относится к решаемой задаче а что нет. Либо проблемы с литером либо нудно стилистический правки вынести в отдельный ПР

2023-01-30 15:41 UTC, AntLer-24rus commented on packages/client/src/pages/Game/components/AudioButton/AudioButton.tsx
> +    setIsMusicOn(!isMusicOn);
Не совсем понимаю зачем вызывать `setIsMusicOn` дважды?

2023-02-02 15:33 UTC, AntLer-24rus reviewed
Обращаю внимание команды @caspa2289 @edelweissvalley @lizgam. Если вы готовы втянуть код с огрехами по оформлению, то мёржите реквест. Но я бы рекомендовал все-таки это переделать как положено, иначе может развиться негативная привычка.

2023-02-02 18:55 UTC, AntLer-24rus approved these changes
👌🏻

2023-02-10 12:24 UTC, AntLer-24rus approved these changes

2023-02-10 16:24 UTC, closed without merging