added forum with API on the client side (threads and comments pages)
yandex-team-08/wonderful-game pull request #29
Opened 2023-02-09 01:34 UTC by lizgam

### Какую задачу решаем

-Добавлены вызовы API для форума
-Обновлены страницы со списком тем и списком сообщений
-Доступ к данным форума реализован через Redux

2023-02-09 12:08 UTC, caspa2289 requested changes
Хорошая работа, в целом всё ок, из критичного - захардкожен локалхост, это надо поправить. Остальное на твоё усмотрение.

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/components/Post/Post.tsx
> +          <Avatar>{author.avatar_path ? author.avatar_path : 'А'}</Avatar>
author.avatar_path ?? 'A'

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/components/Post/Post.tsx
> +    await dispatch(setPickedThread({ thread_id: id, title }));
Не нужно хранить title, если уже есть id. Надо сделать селектор, который вернёт данные из списка тредов по id, и использовать его.
Плюс, если используется роутер, этот id можно взять оттуда, там, где он нужен, опять же.

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/utils/constants.ts
> +export const SERVER_HOST = 'http://localhost:3001/api';
Это не константа, надо брать из окружения. При деплое localhost не будет.

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/Forum.tsx
> +type TInitialVal = {
Не стоит сокращать слова, ухудшает читаемость.

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/Forum.tsx
> +  const initialVal: TInitialVal = {
Это не обязательно типизировать

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/Forum.tsx
> +        <Formik
Лучше тип сообщить формику, остальное он сделает. <Formik<ValuesType>>

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/Forum.tsx
> +              <form onSubmit={handleSubmit} className={styles.forum__footer__form}>
Формик экспортирует компонент Form, там вся эта логика предусмотрена. Ещё у тебя дефолтное поведение не превентится

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/ForumPage/components/MessageField/MessageField.tsx
> +  const initialVal: TInitialVal = { content: '' };
FYI: для пустых дефолтов в принципе не обязательно указывать начальные значения, просто в схеме можно указать обработчик typeError.

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/Forum/components/Post/Post.tsx
> +    // await new Promise(resolve => setTimeout(resolve, 500));
Лишний комментарий

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/pages/ForumPage/components/MessageField/MessageField.tsx
> +    props.resetForm();
Это зачем?

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/store/actions/forum.ts
> +    const parentThreadInfo = selectPickedThread(getState());
getState() два раза вызывается

2023-02-09 12:08 UTC, caspa2289 commented on packages/client/src/store/reducers/forum.reducer.ts
> +export const { setPickedThread } = forumSlice.actions;
Это можно через запятую деструктурировать.

2023-02-09 18:01 UTC, lizgam commented on packages/client/src/utils/constants.ts
> +export const SERVER_HOST = 'http://localhost:3001/api';
Я предполагала, что тот, кто будет деплоить, поменяет константу.
Это ведь не принципиально в ПР, где надо было добавить форум

2023-02-09 18:06 UTC, lizgam commented on packages/client/src/pages/ForumPage/components/MessageField/MessageField.tsx
> +    props.resetForm();
чтобы после отправки сообщения поле очищалось

2023-02-09 18:14 UTC, lizgam commented on packages/client/src/pages/ForumPage/components/MessageField/MessageField.tsx
> +  const initialVal: TInitialVal = { content: '' };
предполагалось, что это для очищения формы после сабмита

2023-02-10 12:59 UTC, AntLer-24rus approved these changes
Отличная работа! Однако вышла промашка с `localhost`. Ну и я бы не стал из методов `axios` возвращать весь его ответ. В большинстве случаем вы не работаете на с заголовками отмена ни с заголовками запроса. Ну и в случае чего легче будет подменить `axios` на что-то другое.

2023-02-10 12:59 UTC, AntLer-24rus commented on packages/client/src/utils/constants.ts
> +export const SERVER_HOST = 'http://localhost:3001/api';
Все верно, такие вещи лучше хранить в переменных окружения, чтобы при деплое, в том числе и автоматическом не нужно было менять исходники а просто подсунуть нужные переменные окружения.

2023-02-10 12:59 UTC, AntLer-24rus commented on packages/client/src/store/reducers/forum.reducer.ts
> +export const { setPickedThread } = forumSlice.actions;
```js
export const { setThreads, setComments, setPickedThread } = forumSlice.actions;
```

2023-02-10 21:56 UTC, merged