Task/20 t08 27/add error handler
yandex-team-08/wonderful-game pull request #31
Opened 2023-02-09 10:34 UTC by innabatalova

### Какую задачу решаем

Обработка ошибок
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-09 12:19 UTC, caspa2289 requested changes

2023-02-09 12:19 UTC, caspa2289 commented on .gitignore
> +yarn.lock
Не надо его игнорить.

2023-02-09 12:19 UTC, caspa2289 commented on packages/server/package.json
> +    "react-redux": "^8.0.5",
Зачем он на сервере?

2023-02-10 12:30 UTC, AntLer-24rus approved these changes
Все ок, есть не критические помарки. Но в целом хорошо!

2023-02-10 12:30 UTC, AntLer-24rus commented on packages/client/src/components/RuntimeError/RuntimeError.module.scss
> +}
не хватает пустой строки

2023-02-10 12:30 UTC, AntLer-24rus commented on packages/client/src/components/RuntimeError/RuntimeError.tsx
> +
Можно заметь на одну пустую строку

2023-02-10 12:30 UTC, AntLer-24rus commented on packages/client/src/pages/Error/Error404.tsx
> +    <div style={{ textAlign: 'center', marginTop: '20vh' }}>
Не используйте инлайн стили, выносите в классы!

2023-02-10 16:21 UTC, merged