Task 20 t08 58 consolidate changes
yandex-team-08/wonderful-game pull request #5
Opened 2022-12-07 08:06 UTC by caspa2289

### Какую задачу решаем

Собрать всё, что было написано, исправить замечания, и подружить между собой.
Я знаю, что тут много букв, и так не делается, но мы базовый сетап не можем завести три недели уже, так тоже не делается. Отчаянные времена требуют отчаянных мер, и всё такое. Патчноут относительно предыдущих пр-ов, моих и Антона, прилагается.

- Переименовал тест в App.test.tsx
- Переименовал пейджи
- Пропсы в заглушки пейджей не добавлены, т.к незачем объективно.
- Убрал лог из viteconfig

- React-router убран из зависимостей
- Заменил использование useFormikContext на useField в formikTextField
- Прокинул onChange в дефолтный хендлер formikTextField
- Убрал todo/fixme комментарии, завёл соответствующие issue
- Вызовы memo и useCallback остаются до обсуждения с наставником, к консенсусу на обсуждении не пришли
- Route_paths теперь enum
- Роуты в массив не собраны, такой необходимости нет.
- React-query не добавлен, т.к он избыточен.
- Удалены неиспользуемые функции для работы с sessionStorage

- Исправлена опечатка в названии метода getIsAuthorizedToAccessPage
- Создан тип для PageWrapperProps
- Переименованы функции в хуке useAuth
- Убрал неиспользуемую переменную в Authorized
- Убрал из линтера правило про точки с запятой
- Правила named-imports и default-imports сделал необязательными, т.к они некорректно работают с библиотечными импортами. Завёл соответствующую issue.

2022-12-07 16:37 UTC, AntLer-24rus requested changes
Работа объемная, сделано куча всего. И, как обычно водится, не на все хватило внимания (поэтому и есть в хорошей практике делать небольшие PR). Особенно печалит факт коммита 1200 фалов кеша yarn. Я бы посоветовал более "трепетно" относится к истории git. Это сослужит отличную службу в дальнейшем когда проект нужно будет поддерживать. Я уже промолчу про то что содержится внутри каждого отдельного коммита и про их commit message. Рекомендую посмотреть в сторону [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0) крутая штука, а если еще под нее настроить линтер 🔥🔥🔥 Не смотри, что много комментов и не принял PR. PR содержит базовые вещи об которые вы будете спотыкаться в дальнейшем если сейчас их не доведете до идеала. Не опускай руки и не отчаивайся, все получится!! Если надумаете пересобрать PR чтобы убрать досадное недоразумение в виде кэша yarn есть небольшая памятка по работе с [git](https://gist.github.com/bendasvadim/fc398385810473f9724bad9d42281fb3) в свое время помогла мне потереть случайно закоммиченые пароли 🤦🏼‍♂️

P.S.: Ребята, я последний раз смотрю PR без вашего кроссревью. и под кроссревью я подразумеваю не просто прожать кнопку `approve`

2022-12-07 16:37 UTC, AntLer-24rus commented on .gitignore
> +.yarnrc.yml
Что-то ты намудрил с настройками yarn раз глобальная папка `.yarn` и настройки `.yarnrc.yml` попали в корень проекта 😳 Самое печальное, что ты успел их закоммитить. И не смотря на то, что ты добавил их `.gitignore` этот коммит остался в истории git\`а и когда ваше репозиторий клонируешь скачивается порядка 100 мб.
```sh
$ git clone git@github.com:yandex-team-08/wonderful-game.git team-08
Клонирование в «team-08»...
remote: Enumerating objects: 1398, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 1398 (delta 52), reused 61 (delta 34), pack-reused 1268
Получение объектов: 100% (1398/1398), 105.91 МиБ | 1.86 МиБ/с, готово.
Определение изменений: 100% (124/124), готово.
```

Решите в команде, оставите вы это так как есть или пересобирёте ПР. Я бы рекомендовал пересобрать. Это может потом выплыть боком, самым неочевидным образом. 🤷🏼‍♂️

2022-12-07 16:37 UTC, AntLer-24rus commented on README.md
> +- Формат именования веток task-{ID}-{DESCRIPTION}
Пишешь про ветку `main` а сам ПР открыт в ветку `dev` 👀

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/client/package.json
> +    "@emotion/react": "^11.10.5",
На самом деле, для пущей стабильности неплохо "рышечки" `^` не писать в номерах версий, тогда даже если потеряется `yarn.lock` или `package-lock.json` в проект установятся именно те зависимости с которыми вы разрабатывали. Чтобы каждый раз не убирать их в ручную можно создать в корне проекта файлик `.npmrc` со следующим содержимым
```
save-exact=true
```
или в вашем случае `.yarnrc`
```
save-prefix false
```

только предварительно его нужно вытащить из `.gitignore`

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/client/src/pages/Login/Login.module.scss
> +}
Не хватает пустой строки в конце файла, хотя в `.editorconfig` есть правило которое должно автоматически добавлять пустую строку. Видимо редактор не настроен на поддержку editor config. 

❗️❗️❗️ ОБРАТИТЕ ВНИМАНИЕ ❗️❗️❗️

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/client/src/pages/Root/components/MainCardHeader/components/UserControls/Authorized/Authorized.tsx
> +import { usePageContext } from '../../../../../../../hooks/usePageContext'
Было бы неплохо настроить алиасы. Стоит посмотреть в оф доке [раз](https://v2.vitejs.dev/config/#resolve-alias) и  [два](https://github.com/rollup/plugins/tree/master/packages/alias#rollupplugin-alias).

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/client/vite.config.ts
>    server: {
Не очень понимаю смысл сделанных изменений..

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/server/__tests__/example.test.ts
> +});
Про такого рода изменения я уже упоминал ранее в [комментариях](https://github.com/yandex-team-08/wonderful-game/pull/3#pullrequestreview-1201393969).

2022-12-07 16:37 UTC, AntLer-24rus commented on packages/server/index.ts
> +});
Видимо сработал какой-то автоматический инструмент, или линтер или приттер. Смотри по этому поводу коммент выше.

2022-12-07 17:37 UTC, caspa2289 commented on packages/client/vite.config.ts
>    server: {
Это eslint переставляет импорты. Плагин там такой подключен.

2022-12-07 17:39 UTC, caspa2289 commented on packages/server/__tests__/example.test.ts
> +});
Линтер проигнорировал эти файлы, вообще я отключил точки с запятой. Поправлю.

2022-12-07 17:43 UTC, caspa2289 commented on .gitignore
> +.yarnrc.yml
Да пересоберу завтра, чего уж. 
По идее гит вообще должен игнорировать папки, которые на точку начинаются, хз как так получилось. Я заметил-то только когда пр сделал что там 1к файлов изменено)

2022-12-07 22:31 UTC, edelweissvalley commented on packages/client/vite.config.ts
>    server: {
А где тут импорт, который он переставил?
удалена пустая строка, которая должна быть.

2022-12-07 22:48 UTC, edelweissvalley commented on packages/server/__tests__/example.test.ts
> +});
@AntLer-24rus 
Я не смог ответить в своём pr, т.к. github имеет свои странности в интерфейсе.

Насчёт eslint - серьёзно?
Я думал, эти споры уже канули в лету.

- По поводу точки с запятой и зачем она нужна подробно расписано [здесь](https://learn.javascript.ru/structure#semicolon)
Первый раз вижу, чтоб кто-то отговаривал её использовать)
- Насчёт отключения правил, т.е. я зайдя в крупный файл, чтобы добавить одну строку, должен буду исправить все правила линта? И не испортит историю гита? Смысл добавлять правила, чтобы кто-то другой их настроил в проекте?
- Какую-такую историю гита можно потерять в коммите, который рассчитан на то, чтобы всё настроить для работы в проекте? И который, к тому же, отфоркан (т.е. уже нашей команды).

2022-12-07 22:49 UTC, edelweissvalley commented on packages/server/index.ts
> +});
после rebase всё будет норм

2022-12-08 05:31 UTC, caspa2289 commented on packages/server/__tests__/example.test.ts
> +});
> * По поводу точки с запятой и зачем она нужна подробно расписано [здесь](https://learn.javascript.ru/structure#semicolon)

Линтер добавит её при любых настройках в таком случае. Не надо ставить их везде для этого.

2022-12-08 05:41 UTC, caspa2289 commented on .gitignore
> +.yarnrc.yml
Мы договорились сквошить коммиты, и я тут перечитал про то, как сквош мердж работает, после него эти файлы забудутся, так что можно не пересобирать. Ветку эту всё равно удалять потом.

2022-12-08 06:37 UTC, closed without merging

2022-12-08 07:45 UTC, AntLer-24rus commented on packages/server/__tests__/example.test.ts
> +});
> Первый раз вижу, чтоб кто-то отговаривал её использовать)

Да я и не отговаривал, читайте внимательно. На своих проекта я ее использую.

> Насчёт отключения правил: т.е. я зайдя в крупный файл, чтобы добавить одну строку, должен буду исправить все правила линта? И это не испортит историю гита? Смысл добавлять правила, чтобы кто-то другой их настроил в проекте?

А что ты видишь в этом криминального? Добавь линтер на живой проект и переколбась все файлы под новые правила линтера, в коммите будет **весь** проект. А потом пообщайся с коллегами... Если тебе не приходилось рыться в истории гита и выяснять кто и зачем изменял код это здорово.

> Какую-такую историю гита можно потерять в коммите, который рассчитан на то, чтобы всё настроить для работы в проекте? И который, к тому же, отфоркан (т.е. уже нашей команды).

Я не говорил, что вашей команде это нужно или не нужно сделать. Я упомянул общий случай. В вашем конкретном случае это можно и пропустить, так-как контекст понятен и можно прировнять его в самому первому коммину в проекте. 🤷🏼‍♂️

Без обид но мы либо не понимаем друг друга, либо ты читаешь не внимательно.